
/* Creación de tablas de la base de datos */
CREATE TABLE Manager (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
CONSTRAINT pk_manager PRIMARY KEY (id)
);

CREATE TABLE Submanagers (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
boss_id NUMBER NOT NULL,
CONSTRAINT pk_submanagers PRIMARY KEY (id),
CONSTRAINT fk_submanagers_manager FOREIGN KEY (boss_id) REFERENCES Manager(id)
);

CREATE TABLE Branchmanagers (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
boss_id NUMBER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (boss_id) REFERENCES Submanagers(id)
);

CREATE TABLE Departmentdirectors (
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
boss_id NUMBER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (boss_id) REFERENCES Branchmanagers(id)
);

CREATE TABLE Branches(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
city VARCHAR(100) NOT NULL,
phone VARCHAR(100) NOT NULL,
branch_manager_id NUMBER NOT NULL,
stock_id NUMBER GENERATED BY DEFAULT ON NULL,
PRIMARY KEY (id),
FOREIGN KEY (branch_manager_id) REFERENCES Branchmanagers(id),
FOREIGN KEY (stock_id) REFERENCES Stocks(id)
);

CREATE TABLE Departments(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
branch_id NUMBER NOT NULL,
department_director_id NUMBER NOT NULL,
name VARCHAR(100) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (branch_id) REFERENCES Branches(id),
FOREIGN KEY (department_director_id) REFERENCES Departmentdirectors(id)
);

CREATE TABLE Salespeople(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
phone VARCHAR(100) NOT NULL,
salary NUMBER NOT NULL,
commission NUMBER DEFAULT 0 NOT NULL,
hire_date date DEFAULT SYSDATE NOT NULL,
promotion_date date DEFAULT SYSDATE NOT NULL,
termination_date date,
active NUMBER(1, 0) DEFAULT 1 NOT NULL,
department_id NUMBER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (department_id) REFERENCES Departments(id)
);

CREATE TABLE Customers(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name VARCHAR(100) NOT NULL,
nit NUMBER UNIQUE NOT NULL,
address VARCHAR(100) NOT NULL,
phone VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
manager_name VARCHAR(100) NOT NULL,
manager_last_name VARCHAR(100) NOT NULL,
salesperson_id NUMBER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (salesperson_id) REFERENCES Salespeople(id)
);

CREATE TABLE Meetings(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
meeting_date date NOT NULL,
customer_id NUMBER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (customer_id) REFERENCES Customers(id)
);

CREATE TABLE Sales(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
salesperson_id NUMBER NOT NULL,
customer_id NUMBER NOT NULL,
sale_date date DEFAULT SYSDATE NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (salesperson_id) REFERENCES Salespeople(id),
FOREIGN KEY (customer_id) REFERENCES Customers(id)
);

CREATE TABLE Purchases(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
branch_id NUMBER NOT NULL,
purchase_date date DEFAULT SYSDATE NOT NULL,
arrive_date date,
PRIMARY KEY (id),
FOREIGN KEY (branch_id) REFERENCES Branches(id)
);

CREATE TABLE Providers(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name VARCHAR(100) NOT NULL,
nit NUMBER NOT NULL,
address VARCHAR(100) NOT NULL,
phone VARCHAR(100) NOT NULL,
manager_name VARCHAR(100) NOT NULL,
manager_last_name VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE Products(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
name VARCHAR(100) NOT NULL,
description varchar(200) NOT NULL,
purchase_price NUMBER NOT NULL,
sale_price NUMBER NOT NULL,
market_division VARCHAR(100) NOT NULL,
provider_id NUMBER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (provider_id) REFERENCES Providers(id)
);

CREATE TABLE Purchases_products(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
purchase_id NUMBER NOT NULL,
product_id NUMBER NOT NULL,
quantity NUMBER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (purchase_id) REFERENCES Purchases(id),
FOREIGN KEY (product_id) REFERENCES Products(id)
);

CREATE TABLE Products_stocks(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
product_id NUMBER NOT NULL,
stock_id NUMBER NOT NULL,
quantity NUMBER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (product_id) REFERENCES Products(id),
FOREIGN KEY (stock_id) REFERENCES Branches(stock_id)
);

CREATE TABLE Sales_products(
id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
sale_id NUMBER NOT NULL,
product_id NUMBER NOT NULL,
quantity NUMBER NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (sale_id) REFERENCES Sales(id),
FOREIGN KEY (product_id) REFERENCES Products(id)
);

/*Insert data in manager table*/
INSERT INTO Manager(name, last_name) VALUES ('Juan', 'Perez');

/*Insert data in submanager table*/
INSERT INTO Submanagers(name, last_name, boss_id) VALUES ('Pedro', 'Perez', 1);
INSERT INTO Submanagers(name, last_name, boss_id) VALUES ('Juana', 'Perez', 1);
INSERT INTO Submanagers(name, last_name, boss_id) VALUES ('Maria', 'Perez', 1);
INSERT INTO Submanagers(name, last_name, boss_id) VALUES ('Ana', 'Perez', 1);

/*Insert data in branchmanager table*/
insert into Branchmanagers (name, last_name, boss_id) values ('Jessie', 'Faccini', 1);
insert into Branchmanagers (name, last_name, boss_id) values ('Magdalena', 'Toppas', 1);
insert into Branchmanagers (name, last_name, boss_id) values ('Meyer', 'Kybert', 1);
insert into Branchmanagers (name, last_name, boss_id) values ('Hatti', 'Alsford', 4);
insert into Branchmanagers (name, last_name, boss_id) values ('Susy', 'Orro', 4);
insert into Branchmanagers (name, last_name, boss_id) values ('Wilhelmine', 'Eldritt', 2);
insert into Branchmanagers (name, last_name, boss_id) values ('Peta', 'Mowling', 1);
insert into Branchmanagers (name, last_name, boss_id) values ('Morna', 'Bonnavant', 1);
insert into Branchmanagers (name, last_name, boss_id) values ('Vannie', 'Isacke', 3);
insert into Branchmanagers (name, last_name, boss_id) values ('Pen', 'Querrard', 2);

/*Insert data in departmentdirectors table*/
insert into Departmentdirectors (name, last_name, boss_id) values ('Pennie', 'Korneichik', 2);
insert into Departmentdirectors (name, last_name, boss_id) values ('Crystal', 'Elesander', 10);
insert into Departmentdirectors (name, last_name, boss_id) values ('Marchelle', 'Wyer', 7);
insert into Departmentdirectors (name, last_name, boss_id) values ('Sigfried', 'Ivanchin', 4);
insert into Departmentdirectors (name, last_name, boss_id) values ('Kalinda', 'Piggens', 9);
insert into Departmentdirectors (name, last_name, boss_id) values ('Scott', 'Kiljan', 1);
insert into Departmentdirectors (name, last_name, boss_id) values ('Buck', 'Cruddace', 2);
insert into Departmentdirectors (name, last_name, boss_id) values ('Sigismundo', 'O''Calleran', 5);
insert into Departmentdirectors (name, last_name, boss_id) values ('Elbert', 'Van der Spohr', 7);
insert into Departmentdirectors (name, last_name, boss_id) values ('Georgiana', 'Rainbow', 6);
insert into Departmentdirectors (name, last_name, boss_id) values ('Deane', 'Vernazza', 10);
insert into Departmentdirectors (name, last_name, boss_id) values ('Walton', 'Arrigo', 5);
insert into Departmentdirectors (name, last_name, boss_id) values ('Keri', 'Samworth', 4);
insert into Departmentdirectors (name, last_name, boss_id) values ('Idalina', 'Jeram', 4);
insert into Departmentdirectors (name, last_name, boss_id) values ('Isis', 'Baccus', 10);
insert into Departmentdirectors (name, last_name, boss_id) values ('Filmer', 'Faulconer', 1);
insert into Departmentdirectors (name, last_name, boss_id) values ('Ezequiel', 'Mathiot', 3);
insert into Departmentdirectors (name, last_name, boss_id) values ('Kippy', 'Dayer', 2);
insert into Departmentdirectors (name, last_name, boss_id) values ('Meier', 'Bullivant', 5);
insert into Departmentdirectors (name, last_name, boss_id) values ('Loralee', 'Bartolome', 3);

/*insert data in Branches table*/
insert into Branches (city, phone, branch_manager_id) values ('Zhoukou', '579-823-0606', 1);
insert into Branches (city, phone, branch_manager_id) values ('Dadus', '345-555-5340', 2);
insert into Branches (city, phone, branch_manager_id) values ('Longquan', '731-403-7874', 3);
insert into Branches (city, phone, branch_manager_id) values ('Madan', '815-185-2693', 4);
insert into Branches (city, phone, branch_manager_id) values ('Dolní Počernice', '316-141-5444', 5);
insert into Branches (city, phone, branch_manager_id) values ('Stari Grad', '646-768-8201', 6);
insert into Branches (city, phone, branch_manager_id) values ('Eido', '738-792-0841', 7);
insert into Branches (city, phone, branch_manager_id) values ('Sirnarasa', '199-609-9957', 8);
insert into Branches (city, phone, branch_manager_id) values ('Krajan', '407-308-8262', 9);
insert into Branches (city, phone, branch_manager_id) values ('Qom', '617-832-0005', 10);

/*insert data in Departments table*/
insert into Departments (branch_id, department_director_id, name) values (10, 1, 'Music');
insert into Departments (branch_id, department_director_id, name) values (3, 2, 'Jewelry');
insert into Departments (branch_id, department_director_id, name) values (4, 3, 'Tools');
insert into Departments (branch_id, department_director_id, name) values (5, 4, 'Automotive');
insert into Departments (branch_id, department_director_id, name) values (6, 5, 'Home');
insert into Departments (branch_id, department_director_id, name) values (7, 6, 'Outdoors');
insert into Departments (branch_id, department_director_id, name) values (10, 7, 'Baby');
insert into Departments (branch_id, department_director_id, name) values (8, 8, 'Grocery');
insert into Departments (branch_id, department_director_id, name) values (9, 9, 'Games');
insert into Departments (branch_id, department_director_id, name) values (5, 10, 'Baby');
insert into Departments (branch_id, department_director_id, name) values (2, 11, 'Clothing');
insert into Departments (branch_id, department_director_id, name) values (1, 12, 'Movies');
insert into Departments (branch_id, department_director_id, name) values (7, 13, 'Beauty');
insert into Departments (branch_id, department_director_id, name) values (9, 14, 'Games');
insert into Departments (branch_id, department_director_id, name) values (1, 15, 'Computers');
insert into Departments (branch_id, department_director_id, name) values (6, 16, 'Garden');
insert into Departments (branch_id, department_director_id, name) values (7, 17, 'Automotive');
insert into Departments (branch_id, department_director_id, name) values (4, 18, 'Garden');
insert into Departments (branch_id, department_director_id, name) values (7, 19, 'Toys');
insert into Departments (branch_id, department_director_id, name) values (2, 20, 'Grocery');

/* Insert data in Salespeople table */
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Christye', 'Millar', '864-469-5472', 960804, 176875, 1);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Germaine', 'De Francesco', '530-265-2571', 807087, null, 2);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Adelaida', 'Grisedale', '413-214-8145', 1193065, 177254, 3);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Carlo', 'Demschke', '579-942-0007', 983476, null, null, 4);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Hubey', 'Seefus', '981-581-4698', 1052423, 193961, 5);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Noelle', 'Dubbin', '540-894-4141', 1168271, 132327, 6);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Care', 'Tarpey', '770-159-5398', 984800, 153520, 7);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Sherilyn', 'Normant', '513-532-6874', 1153051, 180247, 8);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Cecilio', 'Heifer', '524-469-0693', 886388, null, 9);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Vida', 'Parzizek', '945-355-3724', 863963, null, 10);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Jarret', 'Briztman', '549-749-7951', 1103858, 198109, 11);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Colin', 'Sweedy', '177-152-1427', 828660, 112246, 12);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Meghann', 'Castagnet', '524-187-6050', 1190360, null, 13);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Lia', 'Stellin', '401-613-7341', 1133027, 134290, 14);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Ortensia', 'Tinkler', '990-122-2183', 801540, null, 15);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Ulrikaumeko', 'Gillice', '448-843-0293', 1140951, 116700, 16);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Kipper', 'O''Noulane', '585-990-6850', 936047, null, 17);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Bessie', 'Martine', '809-595-8427', 1089849, null, 18);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Briana', 'Newbury', '233-209-4711', 915130, 168645, 19);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Marnia', 'Giacubo', '513-228-6472', 1042471, 187667, 20);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Niki', 'Lightowler', '962-955-4622', 1010510, null, 1);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Danyelle', 'Moyles', '921-702-8114', 828379, 165196, 2);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Kiersten', 'Dornan', '636-256-4440', 1180206, 107855, 3);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Bone', 'Garbutt', '833-352-1657', 1037469, null, 4);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Ortensia', 'Dobbing', '316-269-5540', 926670, null, 5);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Imogene', 'Gareisr', '440-282-7354', 891349, 104914, 6);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Alejoa', 'Maskill', '244-984-3585', 966609, null, 7);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Kelcie', 'Boatswain', '404-140-4133', 1045007, 109090, 8);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Antonino', 'Vanichev', '483-721-9413', 1132384, 104300, 9);
insert into Salespeople (name, last_name, phone, salary, comission, department_id) values ('Fianna', 'MacAughtrie', '871-586-9003', 1175114, null, 10);

/*Insert data in Customers table*/

insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Aguistin', 2000, '9 Armistice Park', '889-596-8288', 'ebassindale0@businessinsider.com', 'Essie', 'Bassindale', 1);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Boony', 2001, '9313 Brickson Park Parkway', '624-619-8743', 'hmccomiskey1@delicious.com', 'Harriett', 'McComiskey', 12);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Gradey', 2002, '417 Golf View Crossing', '525-835-6597', 'kmorsom2@163.com', 'Kaiser', 'Morsom', 3);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Egbert', 2003, '5 Wayridge Road', '993-934-9887', 'sverma3@networkadvertising.org', 'Spence', 'Verma', 4);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Emmalee', 2004, '7016 Chive Court', '903-778-5737', 'sblodg4@gmpg.org', 'Susan', 'Blodg', 5);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Care', 2006, '00 Mesta Junction', '544-908-3587', 'ycoull6@mit.edu', 'Yorker', 'Coull', 6);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Colly', 2007, '99228 Eliot Road', '305-904-5050', 'ggilhooly7@amazonaws.com', 'Gottfried', 'Gilhooly', 7);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Moss', 2008, '65 Jenna Center', '106-288-0484', 'kphilpott8@godaddy.com', 'Karney', 'Philpott', 8);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Renado', 2010, '0 Clarendon Point', '612-611-5836', 'bovernella@independent.co.uk', 'Beatrice', 'Overnell', 9);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Annnora', 2011, '6965 Lakewood Gardens Drive', '912-949-1012', 'gsanchob@blog.com', 'Gordan', 'Sancho', 10);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Evered', 2012, '97908 Lyons Crossing', '920-377-7476', 'vbollinsc@auda.org.au', 'Violetta', 'Bollins', 11);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Brooks', 2013, '336 Elgar Street', '244-108-3250', 'mnoorwoodd@paypal.com', 'Myrlene', 'Noorwood', 12);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Carmelita', 2014, '0 Riverside Alley', '243-291-1739', 'eorre@samsung.com', 'Esteban', 'Orr', 13);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Nerta', 2015, '98498 Linden Street', '934-829-4882', 'ijentzschf@prlog.org', 'Iris', 'Jentzsch', 14);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('York', 2016, '65 Golf Course Park', '830-633-1217', 'tchipleng@time.com', 'Townsend', 'Chiplen', 15);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Kippar', 2022, '719 Cascade Pass', '723-326-8541', 'lmushetm@prlog.org', 'Lind', 'Mushet', 16);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Sandye', 2024, '14 La Follette Place', '582-454-3484', 'bmurdeno@dell.com', 'Belicia', 'Murden', 17);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Alano', 2025, '801 Katie Trail', '934-877-6951', 'amenlovep@lycos.com', 'Adda', 'Menlove', 18);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Darb', 2028, '37379 Mcbride Court', '471-774-1556', 'cyushachkovs@newyorker.com', 'Cale', 'Yushachkov', 19);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Adriane', 2030, '0536 West Parkway', '666-836-8740', 'rchanneru@unesco.org', 'Romy', 'Channer', 20);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Caesar', 2031, '25 Manufacturers Pass', '189-175-5198', 'abillinghamv@discovery.com', 'Aura', 'Billingham', 21);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Marybelle', 2033, '4329 Butternut Crossing', '770-552-3102', 'ucowx@usatoday.com', 'Ulrich', 'Cow', 22);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Durward', 2035, '20819 Almo Lane', '842-450-1578', 'ibwyz@macromedia.com', 'Ilyse', 'Bwy', 23);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Rudolf', 2037, '00361 Mcguire Plaza', '582-489-5012', 'aprati11@wikipedia.org', 'Andrej', 'Prati', 24);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Audy', 2038, '8221 Hoffman Circle', '408-730-2262', 'glints12@wordpress.com', 'Grady', 'Lints', 25);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Rhody', 2041, '0150 Thierer Center', '225-539-5956', 'sgregolin15@addtoany.com', 'Stirling', 'Gregolin', 26);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Merrilee', 2043, '08 Ridgeway Center', '307-132-9375', 'pbello17@tinypic.com', 'Penny', 'Bello', 27);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Herrick', 2045, '22 Tennyson Court', '951-553-7989', 'rborrott19@unicef.org', 'Randie', 'Borrott', 28);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Sharline', 2047, '66 Gerald Circle', '713-361-4464', 'fmargeram1b@mapquest.com', 'Forester', 'Margeram', 29);
insert into Customers (name, nit, address, phone, email, manager_name, manager_last_name, salesperson_id) values ('Tab', 2048, '2 Milwaukee Avenue', '798-862-5262', 'rdunseath1c@rambler.ru', 'Ros', 'Dunseath', 30);


/*
DELETE TABLES
*/
DROP TABLE SALES_PRODUCTS;
DROP TABLE PRODUCTS_STOCKS;
DROP TABLE PURCHASES_PRODUCTS;
DROP TABLE PRODUCTS;
DROP TABLE PROVIDERS;
DROP TABLE PURCHASES;
DROP TABLE SALES;
DROP TABLE MEETINGS;
DROP TABLE CUSTOMERS;
DROP TABLE SALESPEOPLE;
DROP TABLE DEPARTMENTS;
DROP TABLE BRANCHES;
DROP TABLE STOCKS;
DROP TABLE DEPARTMENTDIRECTORS; 
DROP TABLE BRANCHMANAGERS; 
DROP TABLE SUBMANAGERS;
DROP TABLE MANAGER;
purge recyclebin;











